### ISSUE TITLE
Use inclusive gender pronouns throughout the UG

### ISSUE THREAD

**Issue by JuliaPoo** [JuliaPoo/pe#19]
## About

Throughout the UG, the application assumes each student is a `he`, but this does not reflect students in real life. Suggest to use `they` or `he/she`.

## Example

![image.png](https://raw.githubusercontent.com/JuliaPoo/pe/main/files/0e139b54-8cff-41b9-8f21-6437bc8e31fa.png)

**Comment by nus-pe-script** [comment]
[IMPORTANT!: Please do not edit or reply to this comment using the GitHub UI. You can respond to it using CATcher during the next phase of the PE]

# Team's Response
Thank you for the suggestion. However, we believe that the use of ‘he’ is sufficiently gender neutral. As per the The Cambridge Grammar of the English Language, The use, in formal English, of he, him or his as a gender-neutral pronoun has traditionally been considered grammatically correct.

References:
Huddleston, R. D., Pullum, G. K., & Bauer, L. (2022). The Cambridge grammar of the English language. Cambridge University Press.

# Items for the Tester to Verify

## :question: Issue response

Team chose [`response.Rejected`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

<catcher-end-of-segment><hr>
